services:
  app:
    image: mcr.microsoft.com/vscode/devcontainers/base:latest
    volumes:
      - ..:/nextjs-boilerplate:delegated
      - /nextjs-boilerplate/node_modules
    env_file:
      - .env
    tty: true
  db:
    image: postgres:18.0
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: nextjs_boilerplate
    volumes:
      - postgres_data:/var/lib/postgresql
volumes:
  postgres_data:
